// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response to `GET /api/v1/sessions/{id}/brief`: the user/assistant
 * transcript as markdown, tool calls and thinking dropped, the oldest turns
 * elided past the caps.
 */
export type BriefResponse = { markdown: string, 
/**
 * Turns rendered.
 */
turns: number, 
/**
 * Earlier turns elided by the turn or byte cap.
 */
omitted: number, 
/**
 * Whether the byte cap cut anything (elided turns or a cut turn).
 */
truncated: boolean, };
