// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a turn lost when its prompt cache did not match.
 * `reason` is `ttl_expired` | `gateway_rewrote_body` | `unknown`.
 */
export type CacheBust = { lost_tokens: number, lost_usd: number, reason: string, };
