// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One model advertised by `model/list` (codex 0.144.1 `Model`).
 *
 * Only the fields the picker needs are retained; the rest of the codex shape
 * (service tiers, personality, NUX copy) is intentionally dropped.
 */
export type CodexModel = { 
/**
 * Catalog id — the value passed as `-c model="…"` on a spawn.
 */
id: string, 
/**
 * Underlying model slug (codex `model` field). Usually equals `id`.
 */
model: string, 
/**
 * Human label for the picker (codex `displayName`).
 */
display_name: string, 
/**
 * Short description (codex `description`), used for a tooltip/title.
 */
description: string, 
/**
 * Hidden from the default picker unless the user opts into hidden models.
 */
hidden: boolean, 
/**
 * The catalog default for a fresh session (codex `isDefault`).
 */
is_default: boolean, 
/**
 * Reasoning-effort levels this model supports (subset of
 * `low`/`medium`/`high`/`xhigh`/…). The effort picker offers only these.
 */
supported_efforts: Array<string>, 
/**
 * The default effort for this model (codex `defaultReasoningEffort`).
 */
default_effort: string, 
/**
 * Canonical input modalities the model accepts (`text`, `image`).
 */
input_modalities: Array<string>, 
/**
 * Id of the model this one should be upgraded to, when codex marks it as
 * superseded (codex `upgrade`). Drives a disabled/label hint in the UI.
 */
upgrade?: string | null, 
/**
 * Lowest codex release the model is offered to; a machine below it cannot run it.
 */
minimal_client_version?: string | null, };
