// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarnessUpdatePolicy } from "./HarnessUpdatePolicy";
import type { MachineHarnessInfo } from "./MachineHarnessInfo";

export type HarnessAutoupdateInfo = { instance: HarnessUpdatePolicy | null, machines: Array<MachineHarnessInfo>, };
