// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HarnessOutcome = { harness: string, 
/**
 * `updated a→b`, `up to date`, `failed: …`, `deferred: busy`, `not installed`.
 */
outcome: string, at: string, };
