// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HarnessUpdatePolicy = { enabled: boolean, interval_hours: number, harnesses: Array<string>, };
