// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarnessOutcome } from "./HarnessOutcome";
import type { HarnessUpdatePolicy } from "./HarnessUpdatePolicy";
import type { HarnessVersions } from "./HarnessVersions";

/**
 * Heartbeat block. `policy` echoes what the daemon currently holds so the
 * server resends [`crate::ws::DaemonFrameDown::HarnessUpdatePolicy`] only on
 * a difference, and only to a daemon that can parse it.
 */
export type HarnessReport = { policy?: HarnessUpdatePolicy | null, versions: HarnessVersions, outcomes: Array<HarnessOutcome>, 
/**
 * A worker pod: the harness comes from the image and is never updated in place.
 */
managed_by_image: boolean, };
