// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarnessVersion } from "./HarnessVersion";

export type HarnessVersions = { claude_code?: HarnessVersion | null, codex?: HarnessVersion | null, };
