// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarnessUpdatePolicy } from "./HarnessUpdatePolicy";

export type HarnessPolicyRequest = { 
/**
 * `null` clears: the instance default falls back to off, a machine
 * override falls back to the instance default.
 */
policy: HarnessUpdatePolicy | null, };
