// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CLI version on disk and the version of the long-lived process serving
 * sessions (`claude daemon`, `codex app-server daemon`).
 */
export type HarnessVersion = { cli?: string | null, daemon?: string | null, };
