// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-session cache keep-alive schedule. The reaper sends a small tick every
 * `interval_secs` while the session is idle so the provider's prompt cache
 * stays warm, and stops after `max_ticks` ticks without human activity
 * (`0` = indefinitely). A human message resets `ticks_sent`.
 */
export type KeepaliveState = { interval_secs: number, max_ticks: number, ticks_sent: number, 
/**
 * Projected end of the schedule (`max_ticks * interval_secs` from the
 * last human activity); `None` when indefinite.
 */
until?: string | null, };
