// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarnessReport } from "./HarnessReport";
import type { HarnessUpdatePolicy } from "./HarnessUpdatePolicy";

export type MachineHarnessInfo = { machine_id: string, name: string, 
/**
 * `null` inherits the instance default.
 */
policy: HarnessUpdatePolicy | null, effective: HarnessUpdatePolicy, report: HarnessReport | null, report_at: string | null, };
