// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `PUT /api/v1/machines/{id}/mem-ceiling`.
 */
export type MemCeilingRequest = { 
/**
 * Bytes; `null` removes the ceiling.
 */
mem_ceiling_bytes: number | null, };
