// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who asked for an [`AdapterCommand::Remove`].
 *
 * Defaults to [`Self::Automatic`] so a peer that predates the field, or any
 * path that forgets to say, gets the conservative reading.
 */
export type RemoveInitiator = "user" | "automatic";
