// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterId } from "./AdapterId";
import type { Attention } from "./Attention";
import type { Bucket } from "./Bucket";
import type { KeepaliveState } from "./KeepaliveState";
import type { Label } from "./Label";
import type { Liveness } from "./Liveness";
import type { RemoveInitiator } from "./RemoveInitiator";
import type { SessionEndReason } from "./SessionEndReason";
import type { SessionStatus } from "./SessionStatus";
import type { TodoEntry } from "./TodoEntry";
import type { TokenUsage } from "./TokenUsage";
import type { JsonValue } from "./serde_json/JsonValue";

export type SessionListItem = { id: string, parent_id: string | null, machine_id: string, working_dir: string, status: SessionStatus, 
/**
 * Heartbeat-age liveness tier driving the status dot (green/orange/none).
 * Defaults to `Dead` for back-compat with any client that omits it.
 */
liveness: Liveness, 
/**
 * What the session is waiting on, if anything (the ✋ "needs input"
 * glyph). `None` when the session needs no attention.
 */
attention?: Attention | null, 
/**
 * Classifier bucket this session falls in (Working / Needs input /
 * Ready for review / Completed). Drives the grouped session list in
 * both clients. Defaults to `Working` for back-compat.
 */
bucket: Bucket, token_usage: TokenUsage, metadata: JsonValue, 
/**
 * Adapter that produced this session. Defaults to `"claude-code"` for
 * legacy rows that pre-date the `sessions.adapter_id` column.
 */
adapter_id: AdapterId | null, 
/**
 * Machine name (resolved from `machine_id`). `None` if the machine row
 * has been deleted but historical sessions still reference it.
 */
machine_name?: string | null, 
/**
 * Operator-set badge hue for the machine (0-359). `None` =
 * client derives the hue from the machine name hash.
 */
machine_hue?: number | null, 
/**
 * Machine kind (resolved from `machine_id`): `"persistent"`
 * for enrolled daemons, `"dispatch"`/`"ephemeral"` for server-managed
 * dispatch workers. Lets clients group dispatched sessions separately.
 * `None` when the machine row is gone.
 */
machine_kind?: string | null, 
/**
 * Last message text seen on this session, truncated to ~120 chars.
 */
last_message_text?: string | null, 
/**
 * Timestamp of the last message event for this session.
 */
last_message_at?: string | null, 
/**
 * Timestamp the conversation was first registered. Surfaced so
 * clients can show the ISO start datetime in the relative-time tooltip.
 */
registered_at?: string | null, 
/**
 * User-defined session name, when set (falls back to id in the UI).
 */
name?: string | null, 
/**
 * Model the session runs on (e.g. `"opus[1m]"`).
 */
model?: string | null, 
/**
 * Reasoning/effort level (e.g. `"low"`, `"high"`), when set.
 */
effort?: string | null, 
/**
 * Permission posture the session runs under (e.g. `"yolo"`,
 * `"plan"`), when known.
 */
permission_mode?: string | null, 
/**
 * Whether cctui-side auto-approve is on for this session.
 * In-memory server state, reflected so clients can show the toggle.
 */
auto_approve: boolean, 
/**
 * Transcript snippet around a keyword match. Only populated by
 * the search endpoint to show *why* a session matched; `None` otherwise.
 */
match_snippet?: string | null, 
/**
 * Causal seq of the event `match_snippet` was taken from, so clients can
 * open the conversation at the hit. `None` for id/name/dir-only matches.
 */
match_seq?: number | null, 
/**
 * Cold-cache surfacing. Timestamp of the most recent
 * assistant turn (the last `session_token_usage` row). Lets the client
 * predict prompt-cache expiry — Anthropic's cache is a ~5-minute sliding
 * window — before the next send, independent of `cache_cold` (which is
 * only known *after* a turn). `None` when no usage has been recorded.
 */
last_activity_at?: string | null, 
/**
 * *Confirmed* cold cache: the most recent assistant turn
 * re-billed the full context (`cache_creation_tokens > 0` and
 * `cache_read_tokens == 0`), i.e. the prompt cache had gone cold and that
 * turn paid to rewrite it. Drives the ❄️ glyph on the session list.
 */
cache_cold: boolean, 
/**
 * Approximate number of tokens that get re-written to cache on the next
 * send when the cache is cold — the cached-context size from
 * the last turn (`cache_read_tokens + cache_creation_tokens`). A rough
 * estimate, shown on the composer's burst-cost indicator. `None` when no
 * usage has been recorded.
 */
estimated_burst_tokens?: number | null, 
/**
 * Hibernated: the worker process has exited but its job state
 * survives on disk, so a reply revives it (daemon resume-on-reply).
 * Derived from the adapter's final `tempo:"hibernated"` Status. Drives
 * the claude-style red "exited, will resume on reply" dot.
 */
hibernated: boolean, 
/**
 * Pinned/starred: the operator pinned this session so it sorts
 * above everything in the live list and is exempt from the auto-archive
 * reaper regardless of heartbeat age. DB-backed (`sessions.pinned`).
 */
pinned: boolean, 
/**
 * User-defined colored labels attached to this session.
 * Many-to-many (`labels` / `session_labels` tables); empty when unlabeled.
 */
labels: Array<Label>, 
/**
 * Last activity timestamp from `sessions.last_heartbeat`. Bumped
 * per real work event, and — since — also by subagent activity up
 * the `parent_id` chain. Surfaced so clients can derive a long-horizon
 * "stale" display signal (Working session with no activity for >30min)
 * purely from the clock, the same way liveness tiers are time-derived.
 * Distinct from `last_activity_at`, which is the last *assistant turn*
 * (token-usage row) used for cache-expiry prediction. `None` only on stub
 * rows that never carry liveness.
 */
last_heartbeat?: string | null, 
/**
 * OAuth account this session runs under, resolved from the most
 * recent non-revoked `session_tokens` row joined to `account_providers` (name from its `accounts` parent).
 * Surfaced so clients can show which account is driving the session (key
 * icon + name tooltip). `None` for sessions with no minted gateway token
 * (e.g. local sessions that never routed through the cctui gateway).
 */
account_name?: string | null, 
/**
 * Unread assistant `message` events for the calling user:
 * messages newer than that user's `session_reads.last_seen_at` (all when
 * never seen), capped at 99. Only the live list populates it; search and
 * get-one default it to `0`.
 */
unread_count: number, 
/**
 * Live activity headline: the daemon's spinner text from the
 * claude-daemon control-socket `list` snapshot (`sessions.activity`), e.g.
 * "Central verify + cascade cleanup…". Already persisted per Status event;
 * now surfaced on the list so a working row shows *what* it's doing without
 * opening the conversation. `None` when the session has no headline.
 */
activity_detail?: string | null, 
/**
 * When the session (or any subagent, rolled up the `parent_id` chain like
 * the heartbeat) last emitted a `ToolUse`. Lets clients tell a
 * *grinding* session (fresh tool calls) from one that's *asleep* — a bare
 * heartbeat with no tool activity for minutes — far tighter than the 30-min
 * `last_heartbeat` staleness. `None` when no tool call has been observed.
 */
last_tool_at?: string | null, 
/**
 * Name of the most recent tool call feeding `last_tool_at`, e.g.
 * `"Read"`, `"Edit"`. `None` when no tool call has been observed.
 */
last_tool_name?: string | null, 
/**
 * Running count of this session's `ToolUse` events for the current turn,
 * reset on a new user prompt. This session's own count only —
 * a parent's rolled-up child activity shows via `last_tool_at`, not this.
 */
tool_use_count: number, 
/**
 * The session's own agent task list, as of its newest `TodoWrite` (claude)
 * or `update_plan` (codex) call. Empty when the session never wrote one —
 * clients must render nothing at all rather than a zero state. Never
 * inherited from a parent or child: each subagent owns its own list.
 */
todos: Array<TodoEntry>, 
/**
 * Live token↔account credential binding: a non-revoked
 * `session_tokens` row with a present `encrypted_token`. Distinct from
 * `account_name`, which is `None` when the token's `accounts` row was
 * deleted even though the binding still exists.
 */
has_token_credentials: boolean, 
/**
 * Whether the session's gateway token has actually been presented at the
 * gateway (`session_tokens.last_used_at`). An account-bound session
 * (`account_name` set) with this `false` is bound in the DB but its worker's
 * traffic never reached the gateway — the "account-bound but no gateway
 * traffic observed" warning state, i.e. it may be silently riding ambient
 * creds. `true` for any session whose token the gateway has seen.
 */
account_traffic_observed: boolean, 
/**
 * Linked-PR hrefs from `sessions.children`. Drives the PR link
 * shown on the session card / TUI line and the `Ready for review` bucket.
 */
pr_links?: Array<string>, 
/**
 * Why the session ended; `None` while it is alive.
 */
end_reason?: SessionEndReason | null, 
/**
 * Adapter/server diagnostic for the end (exit status, stderr tail).
 */
end_detail?: string | null, ended_at?: string | null, 
/**
 * When the idle-TTL sweep will archive this session (and remove its
 * worker). `None` when pinned, archived, a draft, or the sweep is off.
 */
auto_archive_at?: string | null, 
/**
 * Who archived the session; `None` while live or when unrecorded.
 */
archived_by?: RemoveInitiator | null, 
/**
 * Cache keep-alive schedule while enabled (`sessions.keepalive_json`);
 * `None` when off.
 */
keepalive?: KeepaliveState | null, 
/**
 * When the reaper last claimed a keep-alive tick for this session.
 */
last_keepalive_at?: string | null, };
