// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /sessions/{id}/keepalive` body. `enabled: false` clears the schedule;
 * omitted fields fall back to the provider default interval and 6 ticks.
 */
export type SessionKeepaliveRequest = { enabled: boolean, interval_secs?: number | null, max_ticks?: number | null, };
