// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state for a session. Three non-terminal states driven by the
 * timestamp of the most recent activity, not by a heartbeat liveness probe:
 *
 * - `New`: session registered, no assistant turn has arrived yet.
 * - `Active`: most recent activity within the active window.
 * - `Inactive`: no recent activity, but the session is not archived — a
 *   new message or turn revives it back to `Active`.
 * - `Archived`: explicitly dismissed (manually or by the TTL reaper).
 *   Hidden from the default list. A genuinely revived session (new
 *   activity) returns to `Active`; an archived dead session stays hidden.
 * - `Draft`: staged-but-not-dispatched session. Carries its spawn
 *   payload in `metadata.draft` but has no `command_id`, no daemon dispatch,
 *   and no heartbeat — excluded from liveness/reaping. An explicit Launch
 *   mints env fresh, dispatches a normal spawn, and removes the draft.
 * - `Queued`: a spawn held back because its machine was over the RAM ceiling
 *   set for it. The figures that held it back ride in `metadata.queued`; the
 *   reaper launches it once the machine is back under its ceiling, and the
 *   live session then registers under the same id (claude-code) or its own.
 */
export type SessionStatus = "new" | "active" | "inactive" | "archived" | "draft" | "queued";
