// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode";

export type SpawnRequest = { machine_id: string, working_dir: string, prompt: string | null, prompt_name: string | null, 
/**
 * Optional session display name, launched via the adapter (claude `--name`).
 */
name?: string | null, 
/**
 * Adapter to spawn under. Defaults to `"claude-code"` when omitted.
 */
adapter_id?: string | null, 
/**
 * Per-spawn permission posture: `yolo` skips all prompts +
 * sandbox, `auto` auto-applies without prompts but keeps the sandbox,
 * `ask` prompts on every action. `None` → the daemon's per-host
 * default. See [`cctui_proto::adapter::PermissionMode`].
 */
permission_mode?: PermissionMode | null, 
/**
 * Reasoning/effort level to launch the session with (claude `--effort`,
 * codex `model_reasoning_effort`). Valid values differ per adapter
 * (claude: `low`/`medium`/`high`/`xhigh`/`max`; codex:
 * `minimal`/`low`/`medium`/`high`). `None` → the adapter's default.
 */
effort?: string | null, 
/**
 * Model family to launch under. Passed to claude as `--model`
 * and to codex as `-c model="…"`. Free-form (the adapter resolves family
 * aliases like `opus`/`sonnet`/`haiku`/`fable`); `None` → the adapter's
 * own default model.
 */
model?: string | null, 
/**
 * Codex Fast mode: `"fast"` opts this one session into the priority tier
 * (1.5x speed, increased usage — same model, same quality), `"default"`
 * pins the standard tier. `None` → the bound account's `service_tier`
 * setting, else `"default"`. Ignored by non-codex adapters.
 */
service_tier?: string | null, 
/**
 * Environment secrets to inject into the worker process env at spawn time.
 * Keys must match `^[A-Z_][A-Z0-9_]*$`. Carried to the runtime
 * like a bearer capability: NEVER persisted, NEVER logged, NEVER written to
 * the transcript/timeline. `Debug` redacts the values.
 */
env?: { [key in string]: string }, 
/**
 * Named OAuth account to run the session under. Resolved against
 * the caller's own vault; the server mints a session-scoped gateway token
 * and injects `ANTHROPIC_BASE_URL`/`ANTHROPIC_AUTH_TOKEN` (or the codex
 * equivalents) into `env` so the worker's traffic flows through the
 * passthrough gateway under that account. `None` → no gateway injection.
 */
account?: string | null, 
/**
 * Provider of the selected `account`: `anthropic` |
 * `anthropic-compatible` | `openai` | `openai-compatible`. Disambiguates a
 * name shared across providers so the account drives the base URL + family
 * unambiguously (instead of inferring the family from `adapter_id`). `None`
 * → fall back to the adapter-derived family.
 */
provider?: string | null, 
/**
 * Explicit unbound spawn: when true the server does NOT resolve a
 * default account for an empty `account` — the worker runs on the machine's
 * own ambient login (no gateway env, no session token). This is distinct
 * from an unset `account`, which auto-binds the caller's single
 * matching-family account. Ignored when `account` names an
 * account (a named account always binds).
 */
no_account?: boolean, 
/**
 * Let the server choose between the caller's accounts instead of
 * refusing to guess. With several matching-family accounts an unset
 * `account` is a `400` (the caller decides); with `auto_account` the
 * caller delegates that decision, and the server binds the account with
 * the most allocation left for this spawn's model — erroring only when
 * every candidate is measurably out. Ignored when `account` names an
 * account or `no_account` is set.
 */
auto_account?: boolean, 
/**
 * Bind this spawn inside a named account pool: the server picks among the
 * pool's members only, by the pool's strategy, and remembers the pool so a
 * long run can be moved between those same members later. This is the
 * bounded form of `auto_account` — the latter ranks every account the
 * caller can reach, which is fine for one person with one set of
 * credentials and wrong the moment personal and work accounts share a
 * login. Ignored when `account` names an account or `no_account` is set.
 */
pool?: string | null, 
/**
 * Stage this spawn as a draft instead of dispatching it. When
 * true the server validates + persists a `draft` session row carrying the
 * spawn payload in `metadata.draft` and does NOT mint account env or
 * dispatch to the daemon. A later `POST /sessions/{id}/launch` mints env
 * fresh and dispatches the real spawn. `env` is ignored for a draft (no
 * secrets at rest — re-entered at launch time).
 */
save_draft?: boolean, 
/**
 * Archive the session on its own once its first turn ends cleanly
 * (macro spawns): the server remembers the intent under the spawn key,
 * claims it when the session registers, and the reaper archives the
 * session the first time the classifier reads it as done without a
 * failure. A session that asks a question or fails stays listed.
 */
auto_archive?: boolean, 
/**
 * Draft bookkeeping: the env var names the form holds, so an edit can
 * re-propose them (values are re-entered at launch, never stored).
 */
env_keys?: Array<string>, 
/**
 * Draft bookkeeping: names of the files attached in the browser (the
 * bytes stay client-side until launch).
 */
attachment_names?: Array<string>, 
/**
 * Labels to attach to the session this spawn creates. The server keeps
 * them under the spawn key and attaches them when the worker registers,
 * so a launch that returns no session id (machine spawns, draft launches)
 * still lands labelled. Stored with a draft and carried to its launch.
 */
label_ids?: Array<string>, 
/**
 * How this session relates to `parent_session_id`: `followup` marks a
 * session whose first prompt embeds the parent's transcript brief. It
 * nests under the parent like a fork. `None` → a root session.
 */
relation?: string | null, 
/**
 * The session this one continues (see `relation`). Set on the child's
 * `parent_id` when the worker registers.
 */
parent_session_id?: string | null, };
