// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of a session's agent task list, normalized across harnesses.
 *
 * Claude's `TodoWrite` (`{content, status, activeForm}`) and codex's
 * `update_plan` (`{step, status}`) both land here. `status` is always one of
 * `pending` / `in_progress` / `completed`; anything unrecognized degrades to
 * `pending`. `active_form` is claude-only.
 */
export type TodoEntry = { content: string, status: string, active_form?: string | null, };
