// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheBust } from "./CacheBust";

export type TokenUsage = { tokens_in: number, tokens_out: number, cost_usd: number, cache_read_tokens: number, cache_creation_tokens: number, cache_bust?: CacheBust, };
